import sqlite3

# Veritabanına bağlan
conn = sqlite3.connect("tarifler.db")
cursor = conn.cursor()

# Eğer tablo varsa siler (Temiz başlangıç için)
cursor.execute("DROP TABLE IF EXISTS tarifler")

# Yeni tabloyu oluşturur
cursor.execute("""
    CREATE TABLE tarifler (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        isim TEXT NOT NULL,
        kategori TEXT NOT NULL,
        tarif TEXT NOT NULL
    )
""")

# Örnek tarifler
tarifler = [
    ("Mercimek Çorbası", "Çorba", "Mercimek çorbası yapmak için öncelikle 1 su bardağı kırmızı mercimeği iyice yıkayıp süzün. Ardından bir adet soğan ve bir adet havucu doğrayın. Tencereye 1 yemek kaşığı tereyağı veya sıvı yağ ekleyerek soğanları kavurun. Soğanlar pembeleşince 1 yemek kaşığı un ekleyip birkaç dakika karıştırarak kavurmaya devam edin. Daha sonra doğranmış havuçları ve mercimeği tencereye ekleyin. Üzerine 5 su bardağı su veya tavuk suyu ilave ederek kaynamaya bırakın. Çorba kaynadıktan sonra kısık ateşte mercimekler iyice yumuşayana kadar yaklaşık 20-25 dakika pişirin. Pişen çorbayı blenderdan geçirerek pürüzsüz hale getirin. Son olarak tuz, karabiber ve kimyon ekleyerek karıştırın. Servis yaparken üzerine tereyağında kızdırılmış pul biber gezdirebilir ve limon dilimleri ile sunabilirsiniz. Afiyet olsun! 🍲😊"),
    ("Domates Çorbası", "Çorba", "Domates çorbası yapmak için öncelikle 4-5 adet orta boy domatesi rendeleyin veya blenderdan geçirin. Bir tencereye 2 yemek kaşığı tereyağı veya sıvı yağ ekleyerek 1 yemek kaşığı unu kavurun. Un hafifçe kokusunu bırakınca üzerine rendelenmiş domatesleri ekleyin ve birkaç dakika karıştırarak pişirin. Ardından 4 su bardağı sıcak su veya et suyu ekleyerek karıştırın. Çorbanın pürüzsüz olması için blenderdan geçirebilir veya süzgeçten süzebilirsiniz. Kaynamaya başladıktan sonra tuz ve karabiber ekleyerek kısık ateşte 10-15 dakika pişirin. Son olarak yarım su bardağı süt veya krema ekleyerek çorbayı daha lezzetli hale getirebilirsiniz. Servis ederken üzerine rendelenmiş kaşar peyniri serpebilir ve sıcak olarak sunabilirsiniz. Afiyet olsun! 🍅🍲😊"),
    ("Tavuk Çorbası", "Çorba", "Tavuk çorbası yapmak için öncelikle bir tencereye 1 adet tavuk göğsünü veya butunu koyarak üzerini geçecek kadar su ekleyin ve haşlamaya bırakın. Tavuk iyice piştikten sonra sudan çıkarıp didikleyin ve haşlama suyunu süzerek bir kenara ayırın. Ayrı bir tencerede 2 yemek kaşığı tereyağını eritip 1 yemek kaşığı unu ekleyerek kavurun. Un hafifçe renk değiştirince üzerine haşlama suyunu yavaş yavaş ekleyip karıştırın. Ardından didiklediğiniz tavukları ekleyerek çorbayı kaynamaya bırakın. Daha lezzetli olması için 1 diş ezilmiş sarımsak, tuz, karabiber ve isteğe bağlı olarak yarım limon suyu ekleyebilirsiniz. Kaynadıktan sonra çorbanızı sıcak olarak servis edebilirsiniz. Üzerine maydanoz veya pul biber serperek lezzetlendirebilirsiniz. Afiyet olsun! 🍗🍜😊"),
    ("Tarhana Çorbası", "Çorba", "Tarhana çorbası yapmak için öncelikle bir tencereye 2 yemek kaşığı tereyağı veya sıvı yağı alın ve 1 yemek kaşığı domates salçasını ekleyerek kavurun. Ardından 4 yemek kaşığı tarhanayı ekleyin ve biraz daha kavurarak lezzetini artırın. Yavaş yavaş 5 su bardağı sıcak suyu veya et/tavuk suyunu ekleyin ve sürekli karıştırarak çorbanın topaklanmasını önleyin. Kaynamaya başladıktan sonra tuz, karabiber ve isteğe bağlı olarak pul biber ekleyerek tatlandırın. Çorbanın kıvamını kontrol ederek gerekirse su ekleyebilirsiniz. Kısık ateşte 10-15 dakika boyunca karıştırarak pişirin. Çorba kıvam aldığında sıcak olarak servis edin. Üzerine tereyağında kızdırılmış nane veya kırmızı biber dökerek lezzetini artırabilirsiniz. Afiyet olsun! 🍲😊"),
    ("Karnıyarık", "Ana Yemek", " Karnıyarık yapmak için öncelikle 4-5 adet patlıcanı alacalı şekilde soyun ve ortalarını bıçakla yararak tuzlu suda yaklaşık 20 dakika bekletin. Daha sonra patlıcanları kurulayarak bol kızgın yağda yumuşayana kadar kızartın ve fazla yağını almak için havlu kağıt üzerine çıkarın.İç harcı için bir tavada 2 yemek kaşığı sıvı yağı ısıtıp 1 adet doğranmış soğanı kavurun. Ardından 300-400 gram kıymayı ekleyerek kavurmaya devam edin. Üzerine 2 adet doğranmış domates, 2-3 diş ezilmiş sarımsak, 1 adet doğranmış yeşil biber, tuz, karabiber ve pul biber ekleyerek karıştırın. Harcı birkaç dakika daha pişirip ocaktan alın.Kızarmış patlıcanları fırın tepsisine dizin ve açtığınız yarıkların içine hazırladığınız kıymalı harcı paylaştırın. Üzerlerine domates dilimleri ve biber yerleştirerek süsleyin. 1 su bardağı sıcak suya 1 yemek kaşığı salça ekleyip karıştırarak tepsiye dökün. 180 derece önceden ısıtılmış fırında yaklaşık 20-25 dakika pişirin. Sıcak servis yaparak pilav veya yoğurt ile afiyetle yiyebilirsiniz! 🍆😊"),
    ("İmam Bayıldı", "Ana Yemek", "Öncelikle 4-5 adet patlıcanı alacalı soyun ve acısını almak için tuzlu suda bekletin. Daha sonra iyice kurulayıp bol yağda kızartın. Ayrı bir tavada 2 yemek kaşığı sıvı yağ ile doğranmış 1 adet soğanı kavurun. Üzerine 200 gram kıyma ekleyip suyunu salıp çekene kadar pişirin. 1 adet doğranmış yeşil biber ve 1 yemek kaşığı domates salçasını ekleyerek karıştırın. Son olarak rendelenmiş 2 adet domates, tuz, karabiber ve isteğe bağlı pul biber ekleyip 5 dakika pişirin.Kızarmış patlıcanları fırın tepsisine alın, ortalarını açarak hazırladığınız iç harcı doldurun. Üzerine dilimlenmiş domates ve biber ekleyin. 1 su bardağı sıcak suyu tepsiye dökün ve 180 derece önceden ısıtılmış fırında yaklaşık 20 dakika pişirin. Sıcak olarak servis edin. Afiyet olsun! 🍆😊"),
    ("Köfte", "Ana Yemek", "Derin bir kaba 500 gram kıymayı alın. Üzerine 1 adet rendelenmiş soğan, 1 diş rendelenmiş sarımsak, 1 çay bardağı galeta unu veya bayat ekmek içi, 1 adet yumurta, 1 tatlı kaşığı tuz, 1 çay kaşığı karabiber, 1 çay kaşığı kimyon ve isteğe bağlı pul biber ekleyin. Karışımı iyice yoğurun ve üzerini kapatıp buzdolabında 30 dakika dinlendirin.Dinlenen harçtan ceviz büyüklüğünde parçalar koparıp elinizle yuvarlayarak şekil verin. Köfteleri yağlı kağıt serili fırın tepsisine dizin veya az yağlı tavada önlü arkalı kızartın. Fırında pişirecekseniz 200 derece önceden ısıtılmış fırında yaklaşık 20-25 dakika pişirin. Sıcak olarak servis edin. Yanında pilav ve salata ile harika gider. Afiyet olsun! 🍽️😊"),
    ("Tavuk Sote", "Ana Yemek", "Tavuk sote yapmak için öncelikle 500 gram tavuk göğsünü küp küp doğrayın. Geniş bir tavayı ocağa alıp 2 yemek kaşığı sıvı yağı ekleyin ve tavukları yüksek ateşte suyunu salıp çekene kadar kavurun. Ardından 1 adet doğranmış soğanı ekleyip birkaç dakika daha soteleyin.Üzerine 1 adet doğranmış kırmızı biber ve 1 adet doğranmış yeşil biber ekleyin. Sebzeler yumuşamaya başlayınca 2 adet doğranmış domatesi ekleyin. Karışıma 1 yemek kaşığı domates salçası, 1 çay kaşığı tuz, karabiber, pul biber ve kekik ekleyerek iyice karıştırın.Tavuklar ve sebzeler iyice piştiğinde ocaktan alıp sıcak servis edin. Yanında pilav veya makarna ile harika olur. Afiyet olsun! 🍗😊"),
    ("Kadayıf", "Tatlı", "Kadayıf tatlısı yapmak için öncelikle 300 gram tel kadayıfı geniş bir kaba alın ve elinizle tel tel ayırarak didikleyin. Üzerine 100 gram eritilmiş tereyağını gezdirip iyice karıştırın. Ardından yarısını yağlanmış bir fırın tepsisine yayın ve bastırarak sıkıştırın.Orta katmana 1 su bardağı dövülmüş ceviz serpiştirin. Kalan kadayıfı da cevizlerin üzerine ekleyip tekrar bastırarak sıkıştırın. Önceden ısıtılmış 180°C fırında üstü kızarana kadar yaklaşık 30-35 dakika pişirin.Bu sırada şerbet için 2,5 su bardağı su ve 2 su bardağı şekeri kaynatın. Kaynadıktan sonra birkaç damla limon suyu ekleyerek 5 dakika daha kaynatıp ocaktan alın. Fırından çıkan sıcak kadayıfın üzerine ılık şerbeti gezdirerek dökün. Şerbeti çekmesi için 1-2 saat dinlendirin.Üzerine Antep fıstığı serpiştirerek servis edebilirsiniz. Afiyet olsun! 😊🍯"),
    ("Sütlaç", "Tatlı", "Sütlaç yapmak için öncelikle 1 çay bardağı pirinci iyice yıkayın ve 2 su bardağı su ile birlikte orta ateşte suyunu çekene kadar haşlayın. Pirinçler yumuşadığında üzerine 1 litre süt ekleyin ve karıştırarak kaynamaya bırakın.Kaynamaya başladıktan sonra 1 su bardağı toz şekeri ekleyin ve kısık ateşte ara ara karıştırarak yaklaşık 10-15 dakika pişirin. Ayrı bir kasede 2 yemek kaşığı nişastayı yarım çay bardağı su ile açın ve sütlaca yavaş yavaş ekleyerek kıvam almasını sağlayın.Sütlacın kıvamı koyulaştığında ocaktan alın ve kaselere paylaştırın. Oda sıcaklığına geldikten sonra buzdolabında birkaç saat soğutun. Üzerine tarçın serpiştirerek servis edebilirsiniz. Afiyet olsun! 🍚🥛😊"),
    ("Baklava", "Tatlı", "Baklava yapmak için öncelikle 3 su bardağı unu geniş bir kaba alın ve ortasını havuz gibi açın. İçine 1 adet yumurta, yarım su bardağı süt, yarım su bardağı sıvı yağ, 1 yemek kaşığı sirke ve bir tutam tuz ekleyin. Hamuru yoğurarak ele yapışmayan bir kıvam elde edin ve üzerini örtüp 30 dakika dinlendirin.Hamur dinlenirken, iç harcı için 2 su bardağı ince çekilmiş ceviz veya fıstığı hazırlayın. Dinlenen hamuru 20-30 küçük bezeye ayırın ve her birini nişasta serperek incecik açın. Açılan yufkaların yarısını tepsiye üst üste dizin, aralarına ceviz serpiştirin ve kalan yufkaları da üzerine koyun.Keskin bir bıçakla baklavayı kare veya baklava dilimi şeklinde kesin. Üzerine eritilmiş 200 gram tereyağını gezdirin ve önceden ısıtılmış 180°C fırında altı üstü kızarana kadar, yaklaşık 40-45 dakika pişirin.Şerbeti için 3 su bardağı su ve 3 su bardağı şekeri kaynatın. Kaynadıktan sonra birkaç damla limon suyu ekleyip birkaç dakika daha kaynatın ve ocaktan alın. Fırından çıkan sıcak baklavaya ılık şerbeti dökün ve çekmesi için dinlendirin.Afiyet olsun! 🍯🥄😊"),
    ("Kazandibi", "Tatlı", "Kazandibi yapmak için öncelikle bir tencereye 1 litre sütü alın ve üzerine 1 su bardağı toz şeker ekleyerek karıştırın. Ardından 3 yemek kaşığı nişasta, 3 yemek kaşığı un ve 1 paket vanilini ekleyin. Pürüzsüz bir kıvam elde edene kadar çırpıcıyla karıştırarak pişirin. Muhallebi koyulaşıp göz göz kaynadığında ocaktan alın.Geniş bir tepsinin tabanına 2 yemek kaşığı pudra şekeri serpin ve muhallebinin yarısını ince bir tabaka halinde yayarak ocak üzerinde karamelize olana kadar pişirin. Kararmaya başlayınca üzerine kalan muhallebiyi dikkatlice ekleyin ve oda sıcaklığında soğumaya bırakın.Soğuyan tatlıyı buzdolabına kaldırarak en az 3-4 saat dinlendirin. Daha sonra bir spatula yardımıyla rulo şeklinde sararak dilimleyin. Servis ederken tarçın serpebilirsiniz.Afiyet olsun! 🍮😊"),
    ("Ayran", "İçecek", "Ayran yapmak için bir karıştırma kabına 2 su bardağı yoğurdu alın. Üzerine 1 su bardağı soğuk su ekleyin ve bir çırpıcı veya mikser yardımıyla iyice çırpın. Kıvamına göre su miktarını artırabilirsiniz. Ardından yarım çay kaşığı tuz ekleyerek tekrar karıştırın.Ayranın daha köpüklü olması için çırpma işlemini biraz daha uzun tutabilirsiniz. Daha ferah bir lezzet için içine birkaç buz küpü ekleyebilir veya nane yapraklarıyla süsleyerek servis edebilirsiniz.Buz gibi ayranınız hazır! Afiyet olsun! 🥛😊"),
    ("Limonata", "İçecek", "Limonata yapmak için öncelikle 4 adet limonun kabuklarını rendeleyin ve bir kaba alın. Üzerine 1 su bardağı toz şeker ekleyerek limon kabuklarıyla birlikte iyice ovalayın. Bu işlem limon kabuklarındaki aromanın çıkmasını sağlar.Daha sonra limonların suyunu sıkın ve üzerine 5 su bardağı soğuk su ekleyerek karışıma ekleyin. Şeker tamamen eriyene kadar iyice karıştırın veya karışımı süzerek pürüzsüz hale getirin.Hazırladığınız limonatayı bir sürahiye alın ve içine birkaç dilim limon ile buz küpleri ekleyerek servis edin. Daha ferah bir tat için nane yaprakları da ekleyebilirsiniz.Buz gibi limonatanız hazır, afiyet olsun! 🍋🥤😊"),
    ("Osmanlı Şerbeti", "İçecek", "Osmanlı şerbeti yapmak için öncelikle 1 litre suyu bir tencereye alın. Üzerine 1 su bardağı toz şeker ekleyin ve şeker tamamen eriyene kadar karıştırarak kaynamaya bırakın.Daha sonra 1 çubuk tarçın, 5-6 adet karanfil, 1 tatlı kaşığı hibiskus, 1 tatlı kaşığı kuşburnu, yarım çay kaşığı zencefil ve 1 çay kaşığı karabiber ekleyin. Ayrıca isteğe bağlı olarak 1 adet kabuklarıyla doğranmış portakal veya nar taneleri de ekleyebilirsiniz.Tüm malzemeleri ekledikten sonra kısık ateşte yaklaşık 20-25 dakika kaynatın. Ardından şerbeti ocaktan alın ve süzerek bir sürahiye aktarın. Ilındıktan sonra buzdolabında soğutun.Soğuk olarak servis yaparken içine taze nane yaprakları ve limon dilimleri ekleyerek lezzetini artırabilirsiniz. Osmanlı mutfağının enfes şerbeti hazır, afiyet olsun! 🍷✨"),
    ("Türk Kahvesi","İçecek","Türk kahvesi yapmak için öncelikle cezveye her fincan için bir fincan soğuk su ekleyin. Ardından her fincan için 1-2 çay kaşığı kahve (şekerli içiyorsanız şeker de ekleyerek) ilave edin ve kahveyi tamamen eriyene kadar iyice karıştırın. Cezveyi kısık ateşe alın ve karıştırmadan pişmeye bırakın. Kahve kaynamaya yakın, üzerinde oluşan köpüğü fincanlara eşit şekilde paylaştırın. Kalan kahveyi tekrar kaynatıp fincanlara dökün. Lokum veya bir bardak su ile servis edebilirsiniz. Afiyet olsun! ☕😊")


]

# Tarifleri ekler
cursor.executemany("INSERT INTO tarifler (isim, kategori, tarif) VALUES (?, ?, ?)", tarifler)

# Değişiklikleri kaydetip bağlantıyı kapatır
conn.commit()
conn.close()

print("Veritabanı oluşturuldu ve tarifler eklendi!")
